import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

// const inter = Inter({ subsets: ['latin'] })

export async function getServerSideProps() {
  const data = await import('../data/data.json')
  return {
    props: {
      data: data.events_categories,
    }
  }
}

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          <img src="" alt="" />
          <a href="/">Home</a>
          <a href="/events">Events</a>
          <a href="/about-us">About Us</a>
        </nav>
      </header>
      <main className={styles.main}>
        <h1>Events</h1>
        {data.map(event => {
          return (
            <div key={event.id}>
              <a href={`/events/${event.id}`}>
                <Image width={200} height={300} src={event.image} alt="location image" />
                <div>
                  <h2>{event.title}</h2>
                  <p>{event.description}</p>
                </div>
              </a>
            </div>
          )
        })
        }
      </main>
      <footer>
        <p>c 2022 Next Events App</p>
      </footer>
    </>
  )
}

