import Head from 'next/head'
// import Image from 'next/image'
// import Link from 'next/link'
// import { Inter } from '@next/font/google'
import Header from '.././src/components/header/header'
import HomePage from '.././src/components/home/home-page'
import Footer from '.././src/components/footer/footer'


// const inter = Inter({ subsets: ['latin'] })

export async function getServerSideProps() {
  const data = await import('../data/data.json')
  return {
    props: {
      data: data.events_categories,
    }
  }
}

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <HomePage data={data} />

    </>
  )
}

